/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AppController;
import Controller.VisualController;
import java.text.ParseException;

/**
 *
 * @author PREDATOR
 */
public class AppView extends javax.swing.JFrame {
    // Global Use
    AppController controller;
    VisualController visController;

    /**
     * Creates new form AppView
     */
    public AppView() {
        initComponents();
        
        // Initialize Controller
        controller = new AppController(mainTable.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveRadioButton = new javax.swing.ButtonGroup();
        sortButton = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        mainTitleLabel = new javax.swing.JLabel();
        mainAddButton = new javax.swing.JButton();
        mainDateField = new com.github.lgooddatepicker.components.DateTimePicker();
        mainTGroupField = new javax.swing.JTextField();
        mainTGroupLabel = new javax.swing.JLabel();
        mainTNameLabel = new javax.swing.JLabel();
        mainTNameField = new javax.swing.JTextField();
        mainDateLabel = new javax.swing.JLabel();
        mainRemoveButton = new javax.swing.JButton();
        mainUpdateButton = new javax.swing.JButton();
        mainSaveButton = new javax.swing.JButton();
        mainLoadButton = new javax.swing.JButton();
        mainResetButton = new javax.swing.JButton();
        mainSortButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        settingPanel = new javax.swing.JPanel();
        saveToDatabase = new javax.swing.JRadioButton();
        saveToLocal = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        statusLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        insertionSort = new javax.swing.JRadioButton();
        bubbleSort = new javax.swing.JRadioButton();
        selectionSort = new javax.swing.JRadioButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        visualSortTable = new javax.swing.JTable();
        jSplitPane3 = new javax.swing.JSplitPane();
        visualSortButton = new javax.swing.JButton();
        resetSortButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assignment Tracker");

        jTabbedPane1.setName(""); // NOI18N

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setDividerSize(15);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        mainTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleLabel.setText("Assignment Tracker");
        mainTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        mainAddButton.setText("Add");
        mainAddButton.setBackground(new java.awt.Color(153, 255, 153));
        mainAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddButtonActionPerformed(evt);
            }
        });

        mainTGroupField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mainTGroupFieldKeyTyped(evt);
            }
        });

        mainTGroupLabel.setText("Task Group");

        mainTNameLabel.setText("Task Name");

        mainTNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mainTNameFieldKeyTyped(evt);
            }
        });

        mainDateLabel.setText("Date & Time");

        mainRemoveButton.setText("Remove");
        mainRemoveButton.setBackground(new java.awt.Color(255, 153, 153));
        mainRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainRemoveButtonActionPerformed(evt);
            }
        });

        mainUpdateButton.setText("Update");
        mainUpdateButton.setBackground(new java.awt.Color(255, 255, 153));
        mainUpdateButton.setToolTipText("");
        mainUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainUpdateButtonActionPerformed(evt);
            }
        });

        mainSaveButton.setText("Save");
        mainSaveButton.setBackground(new java.awt.Color(153, 153, 255));
        mainSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSaveButtonActionPerformed(evt);
            }
        });

        mainLoadButton.setText("Load");
        mainLoadButton.setBackground(new java.awt.Color(153, 204, 255));
        mainLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLoadButtonActionPerformed(evt);
            }
        });

        mainResetButton.setText("Reset");
        mainResetButton.setBackground(new java.awt.Color(255, 153, 153));
        mainResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainResetButtonActionPerformed(evt);
            }
        });

        mainSortButton.setText("Re-Sort");
        mainSortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSortButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(mainTGroupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(477, 477, 477))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mainTNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(478, 478, 478))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mainDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(163, 163, 163))
                            .addComponent(mainDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mainTNameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainTGroupField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mainAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mainSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1)))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mainUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mainLoadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1)))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mainResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))
                                    .addComponent(mainRemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mainSortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(10, 10, 10))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitleLabel)
                .addGap(9, 9, 9)
                .addComponent(mainTGroupLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTGroupField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainTNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(mainDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainSortButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainAddButton)
                    .addComponent(mainUpdateButton)
                    .addComponent(mainRemoveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainSaveButton)
                    .addComponent(mainLoadButton)
                    .addComponent(mainResetButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Group", "Task Name", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainTable.setShowGrid(true);
        jScrollPane1.setViewportView(mainTable);

        jSplitPane1.setRightComponent(jScrollPane1);

        jTabbedPane1.addTab("Main", jSplitPane1);

        saveRadioButton.add(saveToDatabase);
        saveToDatabase.setText("Database");
        saveToDatabase.setEnabled(false);
        saveToDatabase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                saveToDatabaseItemStateChanged(evt);
            }
        });

        saveRadioButton.add(saveToLocal);
        saveToLocal.setSelected(true);
        saveToLocal.setText("Local Storage");
        saveToLocal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                saveToLocalItemStateChanged(evt);
            }
        });

        jLabel1.setText("Save Setting");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel2.setText("Database Setting (JDBC)");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        usernameField.setText("root");
        usernameField.setFont(usernameField.getFont().deriveFont(usernameField.getFont().getSize()+2f));
        usernameField.setForeground(new java.awt.Color(102, 102, 102));

        jLabel3.setText("URL");

        passwordField.setFont(passwordField.getFont().deriveFont(passwordField.getFont().getSize()+2f));

        statusLabel.setText("Disconnected");
        statusLabel.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setText("Username");

        jLabel6.setText("Status:");

        jLabel5.setText("Password");

        urlField.setText("jdbc:mysql://localhost:3306/trackerdatabase");
        urlField.setFont(urlField.getFont().deriveFont(urlField.getFont().getSize()+2f));
        urlField.setForeground(new java.awt.Color(102, 102, 102));

        jLabel7.setText("Sorting Method");
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        sortButton.add(insertionSort);
        insertionSort.setSelected(true);
        insertionSort.setText("Insertion Sort");
        insertionSort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                insertionSortItemStateChanged(evt);
            }
        });

        sortButton.add(bubbleSort);
        bubbleSort.setText("Bubble Sort");
        bubbleSort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bubbleSortItemStateChanged(evt);
            }
        });

        sortButton.add(selectionSort);
        selectionSort.setText("Selection Sort");
        selectionSort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectionSortItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(418, 418, 418))
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(605, 605, 605))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingPanelLayout.createSequentialGroup()
                        .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urlField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, settingPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(226, 226, 226))
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, settingPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(228, 228, 228)))
                        .addGap(347, 347, 347))
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(settingPanelLayout.createSequentialGroup()
                                .addComponent(saveToLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                            .addGroup(settingPanelLayout.createSequentialGroup()
                                .addComponent(saveToDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33)))
                        .addGap(208, 208, 208)
                        .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(settingPanelLayout.createSequentialGroup()
                                .addComponent(bubbleSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38))
                            .addGroup(settingPanelLayout.createSequentialGroup()
                                .addComponent(insertionSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(61, 61, 61))
                            .addComponent(selectionSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(178, 178, 178))))
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveToDatabase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveToLocal))
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertionSort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bubbleSort)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionSort)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(statusLabel))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Settings", settingPanel);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setOneTouchExpandable(true);

        visualSortTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Alpha",  new Integer(65)},
                { new Integer(2), "Bravo",  new Integer(25)},
                { new Integer(3), "Charlie",  new Integer(95)},
                { new Integer(4), "Delta",  new Integer(20)},
                { new Integer(5), "Echo",  new Integer(35)}
            },
            new String [] {
                "Original Position", "Name", "Compared Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(visualSortTable);

        jSplitPane2.setRightComponent(jScrollPane2);

        jSplitPane3.setDividerLocation(300);

        visualSortButton.setText("Visualize");
        visualSortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualSortButtonActionPerformed(evt);
            }
        });
        jSplitPane3.setLeftComponent(visualSortButton);

        resetSortButton.setText("Reset");
        resetSortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSortButtonActionPerformed(evt);
            }
        });
        jSplitPane3.setRightComponent(resetSortButton);

        jSplitPane2.setTopComponent(jSplitPane3);

        jTabbedPane1.addTab("Visualize", jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("AppView");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddButtonActionPerformed
        // Sanitization performed in controller
        controller.addPerformed(mainTGroupField, mainTNameField, mainDateField);
    }//GEN-LAST:event_mainAddButtonActionPerformed

    private void mainRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainRemoveButtonActionPerformed
        controller.removePerformed(mainTable.getSelectedRows());
    }//GEN-LAST:event_mainRemoveButtonActionPerformed

    private void mainUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainUpdateButtonActionPerformed
        controller.updatePerformed(mainTGroupField, mainTNameField, mainDateField, mainTable.getSelectedRow());
    }//GEN-LAST:event_mainUpdateButtonActionPerformed

    private void mainResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainResetButtonActionPerformed
        controller.resetPerformed();
    }//GEN-LAST:event_mainResetButtonActionPerformed

    private void saveToLocalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_saveToLocalItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED || saveToLocal.isSelected()) {
            controller.setSave("LOCAL");
        } else {
            controller.setSave("DATABASE");
        }
    }//GEN-LAST:event_saveToLocalItemStateChanged

    private void saveToDatabaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_saveToDatabaseItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED || saveToDatabase.isSelected()) {
            controller.setSave("DATABASE");
        } else {
            controller.setSave("LOCAL");
        }
    }//GEN-LAST:event_saveToDatabaseItemStateChanged

    private void mainSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSaveButtonActionPerformed
        controller.savePerform();
    }//GEN-LAST:event_mainSaveButtonActionPerformed

    private void mainLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainLoadButtonActionPerformed
        try {
            controller.loadLocal();
        } catch (ParseException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error: ParseException String to Date/Time!");
        }
    }//GEN-LAST:event_mainLoadButtonActionPerformed

    private void insertionSortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_insertionSortItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED || insertionSort.isSelected()) {
            controller.setSort("INSERTION");
            if(visController != null) {
                visController.setSort("INSERTION");
            }
        }
    }//GEN-LAST:event_insertionSortItemStateChanged

    private void bubbleSortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bubbleSortItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED || bubbleSort.isSelected()) {
            controller.setSort("BUBBLE");
            if(visController != null) {
                visController.setSort("BUBBLE");
            }
        }
    }//GEN-LAST:event_bubbleSortItemStateChanged

    private void selectionSortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectionSortItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED || selectionSort.isSelected()) {
            controller.setSort("SELECTION");
            if(visController != null) {
                visController.setSort("SELECTION");
            }
        }
    }//GEN-LAST:event_selectionSortItemStateChanged

    private void mainTGroupFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainTGroupFieldKeyTyped
        if(evt.getKeyChar() == ',') {
            evt.consume();
        }
    }//GEN-LAST:event_mainTGroupFieldKeyTyped

    private void mainTNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainTNameFieldKeyTyped
        if(evt.getKeyChar() == ',') {
            evt.consume();
        }
    }//GEN-LAST:event_mainTNameFieldKeyTyped

    private void mainSortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSortButtonActionPerformed
        controller.sort();
    }//GEN-LAST:event_mainSortButtonActionPerformed

    private void visualSortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualSortButtonActionPerformed
        if(visController == null) {
            visController = new VisualController(visualSortTable.getModel());
        }
        
        visController.sort();
    }//GEN-LAST:event_visualSortButtonActionPerformed

    private void resetSortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSortButtonActionPerformed
        if(visController == null) {
            visController = new VisualController(visualSortTable.getModel());
        }
        
        visController.reset();
    }//GEN-LAST:event_resetSortButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bubbleSort;
    private javax.swing.JRadioButton insertionSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton mainAddButton;
    private com.github.lgooddatepicker.components.DateTimePicker mainDateField;
    private javax.swing.JLabel mainDateLabel;
    private javax.swing.JButton mainLoadButton;
    private javax.swing.JButton mainRemoveButton;
    private javax.swing.JButton mainResetButton;
    private javax.swing.JButton mainSaveButton;
    private javax.swing.JButton mainSortButton;
    private javax.swing.JTextField mainTGroupField;
    private javax.swing.JLabel mainTGroupLabel;
    private javax.swing.JTextField mainTNameField;
    private javax.swing.JLabel mainTNameLabel;
    private javax.swing.JTable mainTable;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JButton mainUpdateButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton resetSortButton;
    private javax.swing.ButtonGroup saveRadioButton;
    private javax.swing.JRadioButton saveToDatabase;
    private javax.swing.JRadioButton saveToLocal;
    private javax.swing.JRadioButton selectionSort;
    private javax.swing.JPanel settingPanel;
    private javax.swing.ButtonGroup sortButton;
    public static javax.swing.JLabel statusLabel;
    private javax.swing.JTextField urlField;
    private javax.swing.JTextField usernameField;
    private javax.swing.JButton visualSortButton;
    private javax.swing.JTable visualSortTable;
    // End of variables declaration//GEN-END:variables
}
